import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "../public/logo.png";
import Title from "../components/Title/Title";
import Extensionbutton from "../components/Extensionbutton/Extensionbutton";
import Description from "../components/Description/Description";
import Gallerybutton from "../components/Gallerybutton/Gallerybutton";
import Gallerydesc from "../components/Gallerydesc/Gallerydesc";
import { landing } from "../mocks/landing.js";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div>
        <img src={logo} width={100} height={150} id="main-logo" />
        <Title />
        <Description />
        <Extensionbutton />
        <Gallerydesc />
        <Gallerybutton />
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
